"""Build a self-contained Dimwit review gallery on the Desktop:
  Desktop/Dimwit Review/  ->  index.html (dark WANEFALL gallery, animated turntables) + images/ (copied, self-contained)
Re-run any time to refresh (e.g. after batching more characters). Stdlib + shutil only.
"""
from __future__ import annotations
import shutil, html, glob, os
from pathlib import Path

RAIN = Path(__file__).resolve().parents[2]
ART = RAIN / "artifacts"
SRC = RAIN / "source_art"
REVIEW = Path(os.path.expanduser("~")) / "Desktop" / "Dimwit Review"
IMG = REVIEW / "images"
IMG.mkdir(parents=True, exist_ok=True)

# Auto-discover every generated asset's Hi3D cover so the gallery stays complete as new batches land.
NOUT = ART / "new_out"; POUT = ART / "props_out"
ITEMS = []
def _sec(t): ITEMS.append(("SECTION", t, ""))
def _add(src, name, cap): ITEMS.append((src, name, cap))
def _section(title, contact, covers, strip, prefix, ue_path):
    items = sorted(covers)
    if not items: return
    _sec(f"{title} ({len(items)})  —  in {ue_path}")
    if contact and Path(contact).exists():
        _add(contact, f"_all_{prefix}.png", f"All {title.lower()} at a glance.")
    for c in items:
        nm = Path(c).stem.replace(strip, "").replace("_cover", "")
        _add(c, f"{prefix}_{nm}.png", nm.replace("_", " "))

_section("Characters — alien soldiers", ART/"HI3D_ALL8_covers.png",
         list(ART.glob("hi3d_0*_cover.png")), "hi3d_", "char", "/Game/Wanefall/Dimwit/Characters/")
_section("Mechs — hard-surface (multi-view)", None,
         list(NOUT.glob("mech_*_cover.png")), "mech_", "mech", "/Game/Wanefall/Dimwit/Characters/")
_section("Vehicles", ART/"PROPS_vehicles.png",
         list(POUT.glob("vehicles__*_cover.png")), "vehicles__", "veh", "/Game/Wanefall/Dimwit/Vehicles/")
_section("Guns", ART/"PROPS_guns.png",
         list(POUT.glob("guns__*_cover.png")), "guns__", "gun", "/Game/Wanefall/Dimwit/Weapons/")
_section("Melee weapons", ART/"PROPS_melee.png",
         list(POUT.glob("melee__*_cover.png")), "melee__", "melee", "/Game/Wanefall/Dimwit/Weapons/")
_section("Grenades", None,
         list(NOUT.glob("gren_*_cover.png")), "gren_", "gren", "/Game/Wanefall/Dimwit/Weapons/")

cards, n = [], 0
for src, name, cap in ITEMS:
    if src == "SECTION":
        cards.append(f'<h2>{html.escape(name)}</h2>')
        continue
    if not Path(src).exists():
        continue
    dst = IMG / name
    try:
        shutil.copyfile(src, dst); n += 1
    except OSError:
        continue
    cards.append(
        f'<figure><a href="images/{html.escape(name)}" target="_blank">'
        f'<img src="images/{html.escape(name)}" loading="lazy"></a>'
        f'<figcaption>{html.escape(cap)}</figcaption></figure>')

doc = """<!doctype html><html><head><meta charset="utf-8">
<title>WANEFALL - Dimwit Character Review</title>
<style>
:root{color-scheme:dark}
body{margin:0;background:#070a0e;color:#cfe6e6;font:15px/1.5 'Segoe UI',system-ui,sans-serif}
header{padding:26px 32px;border-bottom:1px solid #14323a;background:linear-gradient(90deg,#0a1014,#0a1820)}
header h1{margin:0;font-size:22px;letter-spacing:3px}
header h1 b{color:#37d0e6}
header p{margin:6px 0 0;color:#6f8b90;font-size:13px}
main{padding:18px 32px 60px}
h2{margin:30px 0 10px;font-size:15px;letter-spacing:1px;color:#37d0e6;border-left:3px solid #37d0e6;padding-left:10px}
.grid{display:flex;flex-wrap:wrap;gap:18px}
figure{margin:0;background:#0c1418;border:1px solid #15303a;border-radius:10px;overflow:hidden;width:340px;box-shadow:0 6px 22px #0008}
figure img{width:100%;display:block;background:#04070a}
figcaption{padding:9px 12px;font-size:12.5px;color:#9fc0c4}
footer{padding:20px 32px;color:#52686c;font-size:12px;border-top:1px solid #14323a}
</style></head><body>
<header><h1>WANE<b>FALL</b> &nbsp;CHARACTER REVIEW</h1>
<p>Dimwit autonomous asset engine &mdash; concept image &rarr; 3D character, on your GPU. Click any image to open full size.</p></header>
<main>__CARDS__</main>
<footer>Generated by Dimwit. Re-run <code>python scripts/qa/make_review_gallery.py</code> to refresh after new characters. Source assets live in C:\\Users\\developer\\Documents\\Dimwit\\artifacts.</footer>
</body></html>"""

# wrap consecutive figures in .grid blocks
out, buf = [], []
def flush():
    if buf: out.append('<div class="grid">' + "".join(buf) + '</div>'); buf.clear()
for c in cards:
    if c.startswith("<h2"):
        flush(); out.append(c)
    else:
        buf.append(c)
flush()
(REVIEW / "index.html").write_text(doc.replace("__CARDS__", "\n".join(out)), encoding="utf-8")
print(f"gallery: {REVIEW/'index.html'}  ({n} images copied)")
